version: '3'

services:
  reviews:
    container_name: steam_reviews_app
    build: .
    depends_on:
      - 'database'
    ports: 
      - '80:3005'
    volumes:
      - ./:/src/app 

  database:
    container_name: steam_reviews_db
    image: mysql:5.7
    ports: 
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=steam
      - MYSQL_ROOT_PASSWORD=student
      
# Sources
# MySQL deploy: https://docs.docker.com/samples/library/mysql/#-via-docker-stack-deploy-or-docker-compose
# Netwokring: https://docs.docker.com/compose/compose-file/#ipv4_address-ipv6_address
# Specifiying networks: https://docs.docker.com/compose/networking/#specify-custom-networks